/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view;

/**
 *
 * @author erruc
 */
public class LMDLandingPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public LMDLandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTopPanel1 = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        jXTextFieldSearch = new org.jdesktop.swingx.JXTextField();
        jLabelSearchIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSplitPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelLeftPane = new javax.swing.JPanel();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPaneUsers = new org.jdesktop.swingx.JXTaskPane();
        jLabelTeachers = new javax.swing.JLabel();
        jLabelStudents = new javax.swing.JLabel();
        JLabelParents = new javax.swing.JLabel();
        jXTaskPaneNotifications = new org.jdesktop.swingx.JXTaskPane();
        jReminderLabel = new javax.swing.JLabel();
        jXTaskPaneInfrastructure = new org.jdesktop.swingx.JXTaskPane();
        jLabelClassrooms = new javax.swing.JLabel();
        jLabelStudentGroups = new javax.swing.JLabel();
        jXTaskPaneImmunization = new org.jdesktop.swingx.JXTaskPane();
        jLabelVaccination = new javax.swing.JLabel();
        jRightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTopPanel1.setBackground(new java.awt.Color(178, 255, 176));
        jTopPanel1.setMaximumSize(new java.awt.Dimension(200, 80));
        jTopPanel1.setMinimumSize(new java.awt.Dimension(200, 80));
        jTopPanel1.setPreferredSize(new java.awt.Dimension(200, 80));
        jTopPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_menu_48px_1.png"))); // NOI18N
        jTopPanel1.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 46, -1));

        jXTextFieldSearch.setBackground(new java.awt.Color(178, 255, 176));
        jXTextFieldSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jXTextFieldSearch.setForeground(new java.awt.Color(255, 255, 255));
        jXTextFieldSearch.setText("Enter text here...");
        jXTextFieldSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        jXTextFieldSearch.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jXTextFieldSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jXTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXTextFieldSearchActionPerformed(evt);
            }
        });
        jTopPanel1.add(jXTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 0, 281, 52));

        jLabelSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_26px.png"))); // NOI18N
        jTopPanel1.add(jLabelSearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 0, 36, 52));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male_user_50px.png"))); // NOI18N
        jLabel4.setText("Hello, Admin");
        jTopPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1151, 0, 151, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lmdic1.PNG"))); // NOI18N
        jTopPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 52));

        getContentPane().add(jTopPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        jSplitPanel.setLayout(new java.awt.BorderLayout());

        jPanelLeftPane.setMaximumSize(new java.awt.Dimension(300, 495));
        jPanelLeftPane.setMinimumSize(new java.awt.Dimension(300, 495));
        jPanelLeftPane.setPreferredSize(new java.awt.Dimension(300, 495));
        jPanelLeftPane.setLayout(new java.awt.BorderLayout());

        jXTaskPaneContainer1.setBackground(new java.awt.Color(178, 255, 176));
        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jXTaskPaneContainer1.setLayout(verticalLayout1);

        jXTaskPaneUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.PNG"))); // NOI18N
        jXTaskPaneUsers.setTitle("Users");

        jLabelTeachers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTeachers.setText("Teachers");
        jXTaskPaneUsers.getContentPane().add(jLabelTeachers);

        jLabelStudents.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStudents.setText("Students");
        jLabelStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStudentsMouseClicked(evt);
            }
        });
        jXTaskPaneUsers.getContentPane().add(jLabelStudents);

        JLabelParents.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JLabelParents.setText("Parents");
        jXTaskPaneUsers.getContentPane().add(JLabelParents);

        jXTaskPaneContainer1.add(jXTaskPaneUsers);

        jXTaskPaneNotifications.setBackground(new java.awt.Color(204, 245, 217));
        jXTaskPaneNotifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bell3.PNG"))); // NOI18N
        jXTaskPaneNotifications.setScrollOnExpand(true);
        jXTaskPaneNotifications.setTitle("Notifications");

        jReminderLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jReminderLabel.setForeground(new java.awt.Color(51, 51, 51));
        jReminderLabel.setText("Reminder");
        jXTaskPaneNotifications.getContentPane().add(jReminderLabel);

        jXTaskPaneContainer1.add(jXTaskPaneNotifications);

        jXTaskPaneInfrastructure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infra1.jpg"))); // NOI18N
        jXTaskPaneInfrastructure.setTitle("Infrastructure");

        jLabelClassrooms.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelClassrooms.setText("Classrooms");
        jXTaskPaneInfrastructure.getContentPane().add(jLabelClassrooms);

        jLabelStudentGroups.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStudentGroups.setText("Student Groups");
        jXTaskPaneInfrastructure.getContentPane().add(jLabelStudentGroups);

        jXTaskPaneContainer1.add(jXTaskPaneInfrastructure);

        jXTaskPaneImmunization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccine11.png"))); // NOI18N
        jXTaskPaneImmunization.setTitle("Vaccination Track");

        jLabelVaccination.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelVaccination.setText("Vaccination");
        jXTaskPaneImmunization.getContentPane().add(jLabelVaccination);

        jXTaskPaneContainer1.add(jXTaskPaneImmunization);

        jPanelLeftPane.add(jXTaskPaneContainer1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanelLeftPane);

        jRightPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(jRightPanel);

        jSplitPanel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jSplitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1320, 990));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jXTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXTextFieldSearchActionPerformed

    private void jLabelStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStudentsMouseClicked
        // TODO add your handling code here:
       StudentUI student= new StudentUI();
       student.setVisible(true);
       
    }//GEN-LAST:event_jLabelStudentsMouseClicked

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LMDLandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelParents;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClassrooms;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelSearchIcon;
    private javax.swing.JLabel jLabelStudentGroups;
    private javax.swing.JLabel jLabelStudents;
    private javax.swing.JLabel jLabelTeachers;
    private javax.swing.JLabel jLabelVaccination;
    private javax.swing.JPanel jPanelLeftPane;
    private javax.swing.JLabel jReminderLabel;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jSplitPanel;
    private javax.swing.JPanel jTopPanel1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPaneImmunization;
    private org.jdesktop.swingx.JXTaskPane jXTaskPaneInfrastructure;
    private org.jdesktop.swingx.JXTaskPane jXTaskPaneNotifications;
    private org.jdesktop.swingx.JXTaskPane jXTaskPaneUsers;
    private org.jdesktop.swingx.JXTextField jXTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
